### ISSUE TITLE
/usr/bin/pip install: error: no such option: --allow-external

### ISSUE THREAD

**Issue by DaveQB** [hauckwill/linconnect-server#61]
```
Usage: /usr/bin/pip install [OPTIONS] PACKAGE_NAMES...

/usr/bin/pip install: error: no such option: --allow-external
```

Getting the above error.

ii  python-pip                            1.0-1build1                           alternative Python package installer
ii  python2.7                             2.7.3-0ubuntu3.5

**Comment by jacklaag** [comment]
just remove the parts which cause errors ;) worked for me

**Comment by GhadaBT** [comment]
and which parts are causing the errors? I'm getting likely the same error!!

**Comment by DaveQB** [comment]
@GhadaBT  I don't know. I gave up sorry.

**Comment by jacklaag** [comment]
"error: no such option: --allow-external"
So you have to remove : --allow-external

**Comment by brianjarita** [comment]
pip expects the package name after every flag. So to install pybonjour you would run:

`pip install pybonjour --allow-external pybonjour --allow-unverified pybonjour`

**Comment by DaveQB** [comment]
@brianjarita  Oh I see. 
I can't even remember why I was installing this and a pip search doesn't find it. So who knows! haha
