### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by Matthew2D** [hauckwill/linconnect-server#68]
I tried to install linconnect on ubuntu. It followed the installation instructions correctly.

    Setting up extlinux (3:4.05+dfsg-6+deb8u1) ...
    P: Checking for EXTLINUX directory... not found.
    P: Creating EXTLINUX directory...mkdir: cannot create directory ‘/boot/extlinux’: No space left on     device
    dpkg: error processing package extlinux (--configure):
     subprocess installed post-installation script returned error exit status 1
    Errors were encountered while processing:
     extlinux
    E: Sub-process /usr/bin/dpkg returned an error code (1)

Also I tried python ~/.linconnect/LinConnectServer/main/linconnect_server.py I get this:

    python: can't open file '/home/matthew/.linconnect/LinConnectServer/main/linconnect_server.py':    
    [Errno 2] No such file or directory

**Comment by jacklaag** [comment]
no space left on device?

**Comment by Matthew2D** [comment]
![image](http://i.imgur.com/TZiXNKI.png)
