### ISSUE TITLE
Add feature to view notify until it close manualy

### ISSUE THREAD

**Issue by stillru** [hauckwill/linconnect-server#75]
Notification shuld be visible not 5 seconds, but until user close it manually by taping on notification baloon

**Comment by floriel** [comment]
You can cahnge the timeout in the server config file located at
~/.config/linconnect-server/conf.ini

**Comment by stillru** [comment]
Set it to zero, strip this setting or something else?

**Comment by redjamesg** [comment]
If set at 0, it will leave the notification baloon untill you click it.
